version: '3.8'

services:
 
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: wallet-app
    ports:
      - "8080:8080" 
    environment:
    
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/walletdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
   
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 
    depends_on:
      - db 
      - rabbitmq 
    networks:
      - wallet-network 

  
  db:
    image: postgres:17-alpine 
    container_name: wallet-db
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data 
    networks:
      - wallet-network 


  rabbitmq:
    image: rabbitmq:3-management-alpine 
    container_name: wallet-rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - wallet-network


networks:
  wallet-network:
    driver: bridge


volumes:
  db_data:
